version: "3"
services:
  app:
    build: .
    ports:
      - "8080:80"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - .:/app
    env_file:
      - .env