name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        env:
          CI: true

      - name: Install packages
        env:
          CI: true
        run: npm install

      - name: Run tests
        env:
          CI: true
        run: npm run test